"""Initial migration

Revision ID: 8964e052ea0e
Revises: 
Create Date: 2026-02-11 23:24:14.209767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8964e052ea0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessments')
    op.drop_table('learning_progress')
    op.drop_table('practice_evaluations')
    op.drop_table('teaching_contents')
    op.drop_table('courses')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('courses_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('courses_pkey'))
    )
    op.create_table('teaching_contents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('generated_by_llm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('teaching_contents_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('teaching_contents_pkey'))
    )
    op.create_table('practice_evaluations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_answer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evaluation_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('practice_evaluations_assessment_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('practice_evaluations_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('practice_evaluations_pkey'))
    )
    op.create_table('learning_progress',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('last_accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('learning_progress_course_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learning_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_progress_pkey'))
    )
    op.create_table('assessments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('questions', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answers', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generated_by_llm', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('assessments_course_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('assessments_pkey'))
    )
    # ### end Alembic commands ###
