"""
Prometheus 指标收集服务
用于监控 API 响应时间、错误率、活跃用户等关键指标
"""
import time
import functools
from typing import Optional, Callable, Any
from prometheus_client import Counter, Histogram, Gauge, Info, generate_latest, CONTENT_TYPE_LATEST
from prometheus_client.registry import CollectorRegistry

# 创建自定义注册表
registry = CollectorRegistry()

# API 请求计数器（按方法和端点分类）
api_requests_total = Counter(
    'api_requests_total',
    'Total API requests',
    ['method', 'endpoint', 'status_code'],
    registry=registry
)

# API 响应时间直方图
api_response_time_seconds = Histogram(
    'api_response_time_seconds',
    'API response time in seconds',
    ['method', 'endpoint'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
    registry=registry
)

# 活跃用户数
active_users = Gauge(
    'active_users',
    'Number of active users',
    registry=registry
)

# 错误率计数器
error_total = Counter(
    'error_total',
    'Total errors',
    ['error_type', 'endpoint'],
    registry=registry
)

# 数据库查询时间
db_query_time_seconds = Histogram(
    'db_query_time_seconds',
    'Database query time in seconds',
    ['query_type', 'table_name'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=registry
)

# 缓存命中率
cache_hits_total = Counter(
    'cache_hits_total',
    'Total cache hits',
    ['cache_name'],
    registry=registry
)

cache_misses_total = Counter(
    'cache_misses_total',
    'Total cache misses',
    ['cache_name'],
    registry=registry
)

# 业务指标
conversations_total = Counter(
    'conversations_total',
    'Total conversations created',
    registry=registry
)

messages_total = Counter(
    'messages_total',
    'Total messages sent',
    ['message_type'],
    registry=registry
)

# AI 生成指标
ai_generation_time_seconds = Histogram(
    'ai_generation_time_seconds',
    'AI content generation time in seconds',
    ['model_type'],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
    registry=registry
)

ai_tokens_generated = Counter(
    'ai_tokens_generated',
    'Total tokens generated by AI',
    ['model_type'],
    registry=registry
)

# 应用信息
app_info = Info(
    'app_info',
    'Application information',
    registry=registry
)


class MetricsService:
    """指标收集服务"""
    
    def __init__(self):
        self._active_user_ids = set()
    
    def record_request(self, method: str, endpoint: str, status_code: int, duration: float):
        """记录 API 请求"""
        api_requests_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=str(status_code)
        ).inc()
        
        api_response_time_seconds.labels(
            method=method,
            endpoint=endpoint
        ).observe(duration)
    
    def record_error(self, error_type: str, endpoint: str):
        """记录错误"""
        error_total.labels(
            error_type=error_type,
            endpoint=endpoint
        ).inc()
    
    def add_active_user(self, user_id: str):
        """添加活跃用户"""
        if user_id not in self._active_user_ids:
            self._active_user_ids.add(user_id)
            active_users.set(len(self._active_user_ids))
    
    def remove_active_user(self, user_id: str):
        """移除活跃用户"""
        if user_id in self._active_user_ids:
            self._active_user_ids.discard(user_id)
            active_users.set(len(self._active_user_ids))
    
    def record_db_query(self, query_type: str, table_name: str, duration: float):
        """记录数据库查询时间"""
        db_query_time_seconds.labels(
            query_type=query_type,
            table_name=table_name
        ).observe(duration)
    
    def record_cache_hit(self, cache_name: str = 'default'):
        """记录缓存命中"""
        cache_hits_total.labels(cache_name=cache_name).inc()
    
    def record_cache_miss(self, cache_name: str = 'default'):
        """记录缓存未命中"""
        cache_misses_total.labels(cache_name=cache_name).inc()
    
    def record_conversation_created(self):
        """记录对话创建"""
        conversations_total.inc()
    
    def record_message(self, message_type: str = 'user'):
        """记录消息"""
        messages_total.labels(message_type=message_type).inc()
    
    def record_ai_generation(self, model_type: str, duration: float, tokens: int):
        """记录 AI 生成"""
        ai_generation_time_seconds.labels(model_type=model_type).observe(duration)
        ai_tokens_generated.labels(model_type=model_type).inc(tokens)
    
    def get_metrics(self) -> tuple:
        """获取 Prometheus 格式的指标数据"""
        return generate_latest(registry), CONTENT_TYPE_LATEST
    
    def set_app_info(self, version: str, environment: str):
        """设置应用信息"""
        app_info.info({
            'version': version,
            'environment': environment
        })


# 全局指标服务实例
metrics_service = MetricsService()


def monitor_performance(func: Callable) -> Callable:
    """性能监控装饰器"""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.time()
        try:
            result = func(*args, **kwargs)
            return result
        except Exception as e:
            raise
        finally:
            duration = time.time() - start_time
            # 这里可以记录函数执行时间
    return wrapper


def monitor_db_query(query_type: str, table_name: str):
    """数据库查询监控装饰器"""
    def decorator(func: Callable) -> Callable:
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            start_time = time.time()
            try:
                result = func(*args, **kwargs)
                return result
            finally:
                duration = time.time() - start_time
                metrics_service.record_db_query(query_type, table_name, duration)
        return wrapper
    return decorator
