"""
Prometheus 指标收集服务
用于监控 API 响应时间、错误率、活跃用户等关键指标
"""
import time
import functools
import json
import math
import threading
from collections import deque
from datetime import datetime, timedelta
from typing import Optional, Callable, Any
from prometheus_client import Counter, Histogram, Gauge, Info, generate_latest, CONTENT_TYPE_LATEST
from prometheus_client.registry import CollectorRegistry

# 创建自定义注册表
registry = CollectorRegistry()

# API 请求计数器（按方法和端点分类）
api_requests_total = Counter(
    'api_requests_total',
    'Total API requests',
    ['method', 'endpoint', 'status_code'],
    registry=registry
)

# API 响应时间直方图
api_response_time_seconds = Histogram(
    'api_response_time_seconds',
    'API response time in seconds',
    ['method', 'endpoint'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
    registry=registry
)

# 活跃用户数
active_users = Gauge(
    'active_users',
    'Number of active users',
    registry=registry
)

# 错误率计数器
error_total = Counter(
    'error_total',
    'Total errors',
    ['error_type', 'endpoint'],
    registry=registry
)

# 数据库查询时间
db_query_time_seconds = Histogram(
    'db_query_time_seconds',
    'Database query time in seconds',
    ['query_type', 'table_name'],
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=registry
)

# 缓存命中率
cache_hits_total = Counter(
    'cache_hits_total',
    'Total cache hits',
    ['cache_name'],
    registry=registry
)

cache_misses_total = Counter(
    'cache_misses_total',
    'Total cache misses',
    ['cache_name'],
    registry=registry
)

# 业务指标
conversations_total = Counter(
    'conversations_total',
    'Total conversations created',
    registry=registry
)

messages_total = Counter(
    'messages_total',
    'Total messages sent',
    ['message_type'],
    registry=registry
)

# AI 生成指标
ai_generation_time_seconds = Histogram(
    'ai_generation_time_seconds',
    'AI content generation time in seconds',
    ['model_type'],
    buckets=[0.5, 1.0, 2.0, 5.0, 10.0, 30.0, 60.0],
    registry=registry
)

ai_tokens_generated = Counter(
    'ai_tokens_generated',
    'Total tokens generated by AI',
    ['model_type'],
    registry=registry
)

# 应用信息
app_info = Info(
    'app_info',
    'Application information',
    registry=registry
)


class MetricsService:
    """指标收集服务"""
    
    def __init__(self):
        self._active_user_ids = set()
        self._request_records = deque(maxlen=5000)
        self._record_lock = threading.Lock()
    
    def record_request(self, method: str, endpoint: str, status_code: int, duration: float):
        """记录 API 请求"""
        api_requests_total.labels(
            method=method,
            endpoint=endpoint,
            status_code=str(status_code)
        ).inc()
        
        api_response_time_seconds.labels(
            method=method,
            endpoint=endpoint
        ).observe(duration)
        with self._record_lock:
            self._request_records.append({
                "method": method,
                "endpoint": endpoint,
                "status_code": int(status_code),
                "duration_ms": round(float(duration) * 1000, 2),
                "recorded_at": datetime.utcnow(),
            })
    
    def record_error(self, error_type: str, endpoint: str):
        """记录错误"""
        error_total.labels(
            error_type=error_type,
            endpoint=endpoint
        ).inc()
    
    def add_active_user(self, user_id: str):
        """添加活跃用户"""
        if user_id not in self._active_user_ids:
            self._active_user_ids.add(user_id)
            active_users.set(len(self._active_user_ids))
    
    def remove_active_user(self, user_id: str):
        """移除活跃用户"""
        if user_id in self._active_user_ids:
            self._active_user_ids.discard(user_id)
            active_users.set(len(self._active_user_ids))
    
    def record_db_query(self, query_type: str, table_name: str, duration: float):
        """记录数据库查询时间"""
        db_query_time_seconds.labels(
            query_type=query_type,
            table_name=table_name
        ).observe(duration)
    
    def record_cache_hit(self, cache_name: str = 'default'):
        """记录缓存命中"""
        cache_hits_total.labels(cache_name=cache_name).inc()
    
    def record_cache_miss(self, cache_name: str = 'default'):
        """记录缓存未命中"""
        cache_misses_total.labels(cache_name=cache_name).inc()
    
    def record_conversation_created(self):
        """记录对话创建"""
        conversations_total.inc()
    
    def record_message(self, message_type: str = 'user'):
        """记录消息"""
        messages_total.labels(message_type=message_type).inc()
    
    def record_ai_generation(self, model_type: str, duration: float, tokens: int):
        """记录 AI 生成"""
        ai_generation_time_seconds.labels(model_type=model_type).observe(duration)
        ai_tokens_generated.labels(model_type=model_type).inc(tokens)
    
    def get_metrics(self) -> tuple:
        """获取 Prometheus 格式的指标数据"""
        return generate_latest(registry), CONTENT_TYPE_LATEST
    
    def set_app_info(self, version: str, environment: str):
        """设置应用信息"""
        app_info.info({
            'version': version,
            'environment': environment
        })

    @staticmethod
    def _percentile(values, percentile):
        if not values:
            return 0.0
        ordered = sorted(values)
        index = max(0, min(len(ordered) - 1, math.ceil(percentile * len(ordered)) - 1))
        return round(ordered[index], 2)

    def workflow_dashboard(self, owner_id=None, days=30):
        from src.models.personalized_workflow import PersonalizedWorkflow, PersonalizedWorkflowEvent
        from src.models.personalized_learning import PersonalizedTaskDelivery, PersonalizedLearningCycle
        from src.services.personalized_notification_service import personalized_notification_service

        days = min(365, max(1, int(days or 30)))
        since = datetime.utcnow() - timedelta(days=days)
        workflow_query = PersonalizedWorkflow.query.filter(PersonalizedWorkflow.created_at >= since)
        delivery_query = PersonalizedTaskDelivery.query.filter(PersonalizedTaskDelivery.created_at >= since)
        cycle_query = PersonalizedLearningCycle.query.filter(PersonalizedLearningCycle.created_at >= since)
        event_query = PersonalizedWorkflowEvent.query.filter(PersonalizedWorkflowEvent.created_at >= since)
        if owner_id is not None:
            workflow_query = workflow_query.filter(PersonalizedWorkflow.owner_id == int(owner_id))
            delivery_query = delivery_query.filter(PersonalizedTaskDelivery.owner_id == int(owner_id))
            cycle_query = cycle_query.filter(PersonalizedLearningCycle.owner_id == int(owner_id))
            event_query = event_query.filter(PersonalizedWorkflowEvent.owner_id == int(owner_id))

        workflows = workflow_query.all()
        deliveries = delivery_query.all()
        cycles = cycle_query.all()
        events = event_query.all()
        generated = [item for item in workflows if item.generation_json]
        generation_durations = []
        degraded_count = 0
        repaired_count = 0
        for item in generated:
            end = item.completed_at or item.updated_at
            if end and item.created_at:
                generation_durations.append(max(0.0, (end - item.created_at).total_seconds() * 1000))
            try:
                generation = json.loads(item.generation_json or "{}")
            except (TypeError, ValueError):
                generation = {}
            source = str(generation.get("generation_source_label") or generation.get("source") or "").lower()
            if any(word in source for word in ("rule", "fallback", "degrad", "保障", "降级")):
                degraded_count += 1
            review = generation.get("review") or {}
            rounds = review.get("rounds") or []
            if any((round_item.get("changes") or []) for round_item in rounds if isinstance(round_item, dict)):
                repaired_count += 1

        event_types = [event.event_type for event in events]
        recovery_count = sum(1 for value in event_types if "recover" in value or value in ("cycle_interrupted", "workflow_resumed"))
        generated_count = len(generated)
        published_count = len(deliveries)
        completed_cycles = sum(1 for item in cycles if item.status == "COMPLETED")
        with self._record_lock:
            records = [item for item in self._request_records if item["recorded_at"] >= since]
        response_times = [item["duration_ms"] for item in records]
        errors = sum(1 for item in records if item["status_code"] >= 500)
        permission_denials = sum(1 for item in records if item["status_code"] in (401, 403))
        scheduler = personalized_notification_service.scheduler_status()

        def rate(numerator, denominator):
            return round(numerator / denominator * 100, 1) if denominator else 0.0

        return {
            "window_days": days,
            "generated_at": datetime.utcnow().isoformat(),
            "scope": "teacher" if owner_id is not None else "system",
            "workflow": {
                "workflow_total": len(workflows),
                "generation_total": generated_count,
                "auto_repair_count": repaired_count,
                "auto_repair_rate": rate(repaired_count, generated_count),
                "degraded_count": degraded_count,
                "degraded_rate": rate(degraded_count, generated_count),
                "published_count": published_count,
                "publish_success_rate": rate(published_count, generated_count),
                "cycle_total": len(cycles),
                "cycle_completed_count": completed_cycles,
                "cycle_completion_rate": rate(completed_cycles, len(cycles)),
                "recovery_count": recovery_count,
                "average_duration_ms": round(sum(generation_durations) / len(generation_durations), 2) if generation_durations else 0.0,
                "p95_duration_ms": self._percentile(generation_durations, 0.95),
            },
            "runtime": {
                "request_total": len(records),
                "error_count": errors,
                "error_rate": rate(errors, len(records)),
                "permission_denied_count": permission_denials,
                "average_response_ms": round(sum(response_times) / len(response_times), 2) if response_times else 0.0,
                "p95_response_ms": self._percentile(response_times, 0.95),
                "active_users": len(self._active_user_ids),
            },
            "scheduler": scheduler,
            "data_notes": [
                "工作流指标来自当前数据库中的状态和事件，不包含学生答案或画像原文。",
                "运行时请求指标保存在当前进程内，服务重启后重新累计。",
            ],
        }


# 全局指标服务实例
metrics_service = MetricsService()


def monitor_performance(func: Callable) -> Callable:
    """性能监控装饰器"""
    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        start_time = time.time()
        try:
            result = func(*args, **kwargs)
            return result
        except Exception as e:
            raise
        finally:
            duration = time.time() - start_time
            # 这里可以记录函数执行时间
    return wrapper


def monitor_db_query(query_type: str, table_name: str):
    """数据库查询监控装饰器"""
    def decorator(func: Callable) -> Callable:
        @functools.wraps(func)
        def wrapper(*args, **kwargs):
            start_time = time.time()
            try:
                result = func(*args, **kwargs)
                return result
            finally:
                duration = time.time() - start_time
                metrics_service.record_db_query(query_type, table_name, duration)
        return wrapper
    return decorator
